### ISSUE TITLE
client & server: add .editorconfig file to both client and server folder

### ISSUE THREAD

**Issue by akashg3627** [Web-Team-IITI-Gymkhana/Gymkhana-IITI#12]
refer https://editorconfig.org/
file content:
`# http://EditorConfig.org

# top-level EditorConfig file
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true`

download this extension for using https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by Satwik2002** [comment]
done

**Comment by akashg3627** [comment]
closed #14
